nvim-lua/completion-nvim

README.md
autoload/completion.vim
plugin/completion.vim

Hi,
first of all, great plugin! I'm finally able to ditch coc.
I found one issue with confirm key. It overrides the mapping completely.
In cases where confirm key is also used for something else, like for example `<CR>` for auto pairs plugin to expand on enter, it stops expanding after setting  completion. I know I can map it to something else, but i think it's neat to have Enter available for both.
For cases like this, I introduced new variable that will be used as fallback in these situations.

Allow providing right hand side of confirm key mapping.

---

lua/source.lua
lua/source/lsp.lua
lua/source/snippet.lua
lua/source/ts_complete.lua
lua/utility.lua

This PR allow fuzzy matching of completion items (for non `ins-complete` sources).
It uses a modified version of the Levenshtein distance, so that it is nearly non fuzzy but also suggests some items that are not exactly matching the current word.
Performance is not impacted at all in the tests I've done.

Fuzzy matching in completion items

---

lua/completion.lua

adds a conditional so that the autocmd doesn't break when the completion confirm key is empty

#34 Make the completion comfirm character optional

---

lua/source/path.lua

Fixes completion of files with spaces and adds file type identifier

---

lua/completion/complete.lua

👋 I tried out this plugin with Neovim nightly via the unstable PPA on a clean install of Ubuntu 20.04, and I got the following error on when I run `lua require'completion'.on_attach()`:
```
E5108: Error executing lua error loading module 'completion.complete' from file 'completion-nvim/lua/completion/complete.lua':
completion-nvim/lua/completion/complete.lua:40: '=' expected near 'continue'
```
It turns out that the unstable PPA version of `nvim` is linked against Lua 5.1 (`:lua print(_VERSION)`), which does not have support for `goto`. This pull request refactors that part of the code so that it shouldn't need a `goto`. Please let me know if there are further adjustments I need to make (or feel free to do them yourself in the interest of speed).

refactor: replace goto for Lua 5.1 compatibility

---

README.md
doc/completion-nvim.txt

Some of these are just grammar changes, and then some are ensuring that the vim docs are actually matching what you have set for text width etc.

Correct docs and readme typos

---

README.md
doc/completion-nvim.txt
lua/completion.lua
lua/completion/health.lua
lua/source/snippet.lua

Thank you your plugin.
I added snippets support for [vim-vsnip](https://github.com/hrsh7th/vim-vsnip).
We can use vim-vsnip as regular snippet source in this PR.

Add Snippets support for vim-vsnip.

---

doc/completion-nvim.txt
lua/source.lua

`triggered_only` is a key you can specify after every `chain_completion_list` to make it only triggered on those keys. This PR fix the behavior of triggered_only cause it break auto changing source now.

Fix triggered_only bahavior and documentation

---

doc/completion-nvim.txt
lua/source/ins_complete.lua

i.e if someone has <C-x> mapped, we shouldn't try to use it.

Change insert completion to ignore keymaps

---

README.md
autoload/completion.vim
doc/completion-nvim.txt

fix: confirm key should reset completion if no items selected

---

lua/source/lsp.lua

The language server specification says that `newText` is the text to be inserted.
````
A textual edit applicable to a text document.
```typescript
interface TextEdit {
/**
* The range of the text document to be manipulated. To insert
* text into a document create a range where start === end.
*/
range: Range;
/**
* The string to be inserted. For delete operations use an
* empty string.
*/
newText: string;
}
```
````
See https://github.com/microsoft/language-server-protocol/blob/ba5483e93d888e22ab38dce258b2471e30005726/_specifications/specification-3-16.md#L515 for reference.
In the current implementation of completion-nvim, `item.word` is set to `item.textEdit.newText`. See the following lines:
https://github.com/nvim-lua/completion-nvim/blob/d28179c685b701d2475aa6125c82717b79a74e82/lua/sou …

Fix LSP completion when applying a `TextEdit` with `newText`

---

lua/source/lsp.lua

Use vim.lsp.util._parse_snippet to parse snippets items.

fix: using the default parse snippets

---

lua/completion/complete.lua
lua/completion/source.lua
lua/completion/source/lsp.lua

Currently in order to do fuzzy matching and stuff, we send completion request to server on every keystrokes, which is... kind of dump. The rework target is to send request only on every new word or deletion, and then cache the complete_items. We can just sending one request per words and theoretically this also allow true fuzzy finding which is server independent (since we only get words on first keystroke).

[WIP]rework: introducing cache mechanism for completion items

---

lua/completion.lua

This PR aims to use the `vsnip_integ#do_complete_done` that replaces `vsnip_integ#on_complete_done_for_lsp`.
And one more thing, if vsnip_integ available, prefer vsnip_integ's additionalTextEdits behavior.
Because additionalTextEdits is a bit difficult to implement correctly.
When completion-nvim has a correct additionalTextEdits implementation, you can disable `vsnip_integ`'s behavior by `apply_additional_text_edits = false`.
The additionalTextEdits should follow the cursor position after applying textEdits.
I was tested the case of https://gitter.im/completion-nvim/community?at=5efda68c6c06cd1bf469b48c

Prefer vsnip's additionalTextEdits expansion

---

README.md
lua/completion.lua
lua/completion/chain_completion.lua
lua/completion/complete.lua
lua/completion/health.lua
lua/completion/hover.lua
lua/completion/matching.lua
lua/completion/option.lua
lua/completion/source.lua
lua/completion/source/lsp.lua
lua/completion/util.lua

Support using lua setup in the `on_attach` function. This allow full lua setup for `completion-nvim` and simply a better server based setup for every variable.
Simply the proposed method is user can pass in a table in `on_attach` functions. By using metatables on our side, we can point back to the origin global variable if it's not in the configure table. This will not introduce any backward compatible issue and will allow us only changing the metatable if you introduce some variable changes on our side. And since it's setup in `on_attach` all the variable here are always per-server base.
Setting it up is actually very straight forward, just use the same variable name as the global variable without the `completion_` part (cause we don't need to prevent namespace collision here). An …

[WIP]feat: support lua per server setup

---

lua/completion/source/lsp.lua

While vim.lsp.buf_get_clients() returns an array that uses numbers as
indices, those numbers are not guaranteed to start at 1, so using #
isn't really correct.
Closes #159.

source/lsp: fix check for clients presence

---

lua/completion/util.lua

This is the fix for https://github.com/nvim-lua/completion-nvim/issues/152.
Basically, if someone provides `dup` option explicitly, it is considered. If not, defaults to 1.
I think this should fix the issue for custom sources where we can provide this property, but it should also maintain backward compatibility.

Consider completion item "dup" property if provided. Fixes #152.

---

lua/completion/health.lua

`:checkhealth` kept failing for me when using `Neosnippet.vim` as my snippet source. Looking at the code it turns out that the check expects a different result from `string.match` than what is actually returned. This PR updates the check to match the other health checks for snippets 🙂 Making the health check work properly also stopped the completion from printing several error messages related to snippets.

fix: health check for neosnippet source

---

lua/completion.lua
lua/completion/source/lsp.lua

I *think* snippets.nvim supports pretty much all of the LSP snippets syntax.

Use snippets.nvim to handle LSP snippets

---

lua/completion/source/snippet.lua

I just testing out `snippets.nvim` today and tried to integrate it with `completion-nvim`, but I ran into this issue because I haven't defined any global snippets for `snippets.nvim` yet.
This PR fixes the issue.

Fix error when there are no global snippets defined in snippets.nvim

---

lua/completion/health.lua

Hey there,
I noticed the health check for UltiSnips failed for me, but it was correctly installed. The health check looks for `".*ultisnips.*"` in `rtp`, but I think it's case-sensitive and my `rtp` contained `UltiSnips`. Does this makes sense?
Thanks!

fix: health check for ultisnips source

---

lua/completion/chain_completion.lua

The option `g:completion_syntax_at_point` was imported by PR #20, but it has never worked.
This PR made it can be either a vim function name or a lua function.
Examples:
* vim function name
```vim
function! lsp#completion#syntax_at_point() abort
return synIDattr(synID(line('.'), col('.'), 1), 'name')
endfunction
let g:completion_syntax_at_point = 'lsp#completion#syntax_at_point'
```
* lua function
```lua
local on_attach = function(client)
require('completion').on_attach {
syntax_at_point = function()
local pos = vim.api.nvim_win_get_cursor(0)
return vim.fn.synIDattr(vim.fn.synID(pos[1], pos[2]-1, 1), "name")
end,
}
end
require('nvim_lsp').<your_pls>.setup {
on_attach = on_attach
}
```
This option is useful when cooperating with `treesitter`, because we cannot get the syntax group by using …

Made completion_syntax_at_point option do work

---

lua/completion/health.lua

My previous [PR](https://github.com/nvim-lua/completion-nvim/pull/176) contained a typo which caused the health check to fail for vim-vsnip. Sorry for that!

fix: typo in health.lua causing check fail for vim-vsnip

---

lua/completion/signature_help.lua

commit 7ee735199fcce0e9dd94cbf288dc7d9e630eef95 breaks my pr #189 
In this pr, we try to use the client's default callback function firstly.

Used default signature help callback firstly if exists

---

README.md

I made a tags completion source that adds some additional information when autocompleting tags from ctags.
This PR just adds a link to it.

Add link to tags completion plugin.

---

lua/completion/chain_completion.lua

```
health#completion_nvim#check
========================================================================
- ERROR: Failed to run healthcheck for "completion_nvim" plugin. Exception:
function health#check[21]..health#completion_nvim#check, line 1
Vim(lua):E5108: Error executing lua ...plug/completion-nvim/lua/completion/chain_completion.lua:60: attempt to index local 'syntax_regex' (a number value)
```
```
- ERROR: Failed to run healthcheck for "completion_nvim" plugin. Exception:
function health#check[21]..health#completion_nvim#check, line 1
Vim(lua):E5108: Error executing lua ...plug/completion-nvim/lua/completion/chain_completion.lua:96: bad argument #1 to 'ipairs' (table expected, got nil)
```
fix error based on checkhealth result.

fix checkhealth error

---

doc/completion-nvim.txt

The comma was missing from the example in the help file.

Add missing comma to the help file.

---

doc/completion-nvim.txt

A minor typo fix in the documentation:
I believe that `completion_smart_tab` is intended to be used in insert mode.

Fix typo in completion_smart_tab map example

---

lua/completion.lua
lua/completion/source/snippet.lua

Actually i only wanted to add the missing custom label for `snippets.nvim`. This would be an extension of this commit 397cde9642de820ee7e37f818775991ec2df693f. Label can be set with
```lua
local customize_lsp_label = {
["snippets.nvim"] = ' [nsnip]'
}
local on_attach = function(_, _)
require'completion'.on_attach({
customize_lsp_label = customize_lsp_label,
})
end
```
Then i realized that using a custom label stops expanding my snippets when triggering completion. 
Would be nice if someone could confirm that this is also happening with one of the other snippet engines(`UltiSnips`, `Neosnippet` and `vim-vsnip`). As far as i see it should happen.
One solution is presented in this pr. I'm not sure if i using `user_data` wrong here. 
Another solution would be this.
```diff
diff --git …
```

Fixes expand when using custom label for snippets

---

lua/completion/source/lsp.lua

Back in #160, I implemented the check with a loop because I didn't
realize vim.tbl_isempty existed. Now that I know about it, I want to
make sure we use it :)

lsp: simplify check for clients presence

---

README.md

Changes the README docs for `<Plug>(completion_smart_tab)` and `<Plug>(completion_smart_s_tab)` to use `imap` instead of `nmap`.

docs: use imap for smart tab completion

---

lua/completion/hover.lua

Neovim does not set `config.lsp.handlers` by default. This is a simple check'n'assign fix.

Fix missing `handlers` table

---

lua/completion/hover.lua

Old code checks that all connected sever support hover.
It should only check that at least one of them support it.

hover if _any_ of the connected server support it

---

lua/completion/hover.lua

scrollbar takes an extra column next to pum.
Move the floating hover window over +1 when the scrollbar is visible.
(Example of how it is broken now:)

move floating window when pum has a scrollbar

---

doc/completion-nvim.txt
lua/completion/source.lua
plugin/completion.vim

Adds option to ignore  the triggerCharacters  provided by the language server.
This helps when servers like sumneko provide undesirable trigger characters such as space,
which makes  g:completion_trigger_keyword_length be ignored.

option to disable server trigger characters

---

lua/completion/matching.lua

We can't feed arbitrary prefixes to substring_match match in
non-simple mode. We run into problems when the buffer has alternative
word rules (Like Lisp buffers with vlime).
The simple parameter of `find` will perform a substring search instead of a regex matching.
```
The pattern argument also allows more complex searches. See the PatternsTutorial for more information. We can turn off the pattern matching feature by using the optional fourth argument plain. plain takes a boolean value and must be preceeded by index. E.g.,
> = string.find("Hello Lua user", "%su")          -- find a space character followed by "u"
10      11
> = string.find("Hello Lua user", "%su", 1, true) -- turn on plain searches, now not found
nil
```
The problem arises when prefix ends with % like for instance `foo%`. …

Fix #313 (substring_match for Lisp): use simple=true

---

lua/completion/signature_help.lua

I am running a Language Server that does not currently support hover.  This change removes the requirement that hover must be supported for signature help to be displayed automatically.

Show signature help when hover is not supported

---

lua/completion/source/lsp.lua
lua/completion/source/snippet.lua
plugin/completion.vim

Allow customize completion_items `dup` option
setup in vim:
`g:completion_items_duplicate = {‘lsp’: 0, ‘UltiSnips’: 0}`

feat: add customizability of dup option for lsp items

---

lua/completion/source/lsp.lua

A few language servers add extra whitespace at the start which messes
up completion. This should fix the issue.

Trim Whitespace From Completion Words and Abbrvs

---

lua/completion.lua
lua/completion/source/snippet.lua

Related https://github.com/hrsh7th/vim-vsnip/issues/160
Currently, completion-nvim expands snippet with `vsnip#expand`. This will re-detect snippet with `prefix`.
But if multiple items have the same prefix, it could be wrong behavior.
So I provide `snippet_body` as user_data and snippet expansion with `vsnip#anonymous`.

Support vsnip's same prefix items

---

lua/completion/source.lua

Saves a string reverse. Also makes the code (arguably) cleaner.

matchend() instead of reverse()+match() for suffix

---

lua/completion/source/lsp.lua

Fixes #252 
Currently intelephense gives `InsertTextFormat` of nil when completion item is requested on `$`.
According to LSP spec, It should be default to `PlainText` when `InsertTextFormat` is ommited.
>	/**
* The format of the insert text. The format applies to both the
* `insertText` property and the `newText` property of a provided
* `textEdit`. If omitted defaults to `InsertTextFormat.PlainText`.
*/
insertTextFormat?: InsertTextFormat;
https://raw.githubusercontent.com/microsoft/language-server-protocol/gh-pages/_specifications/specification-3-16.md
This pull request makes assumption that `InsertTextFormat` should be `PlainText` when ommited and returns `newText` or `insertText` correctly.

fix: InsertTextFormat should fallback to PlainText

---

lua/completion/signature_help.lua

Changed the function call from the now deprecated `focusable_preview` to the new `open_floating_preview`
Since this neovim's commit (https://github.com/neovim/neovim/commit/64da499ac25bd833c57e0850e31affd22294049e), [focusable_preview](https://github.com/neovim/neovim/blob/64da499ac25bd833c57e0850e31affd22294049e/runtime/lua/vim/lsp/util.lua#L1034) is now deprecated in favour of the new [open_floating_preview](https://github.com/neovim/neovim/blob/64da499ac25bd833c57e0850e31affd22294049e/runtime/lua/vim/lsp/util.lua#L1321).

Fix focusable_preview deprecation warnings

---

lua/completion/util.lua

This PR improves the sorting performance a bit.
By using `or` statements rather than `and`, the `nil` checks can be skipped for many items (if the priorities or scores are equal). Equal priorities are not an uncommon occurrence.

Improvement to sorting performance.

---

lua/completion/signature_help.lua

With this change, the buffer's file type is taken into account when converting the signature help into markdown.
I believe, but am not sure, that this is the more generic way of adding syntax highlighting compared to #359.
Edit: this should fix #351.

Handle filetype in floating signature help window

---

lua/completion/signature_help.lua

As `vim.lsp.util.try_trim_markdown_code_blocks` modifies its input in place, it has to be evaluated before the input is used elsewhere. Prior to this change, if trimming could be performed, the floating window would be given the untrimmed markdown to render, but was given e.g. `rust` as the window filetype.
Example:
Fixed:

fix: signature help trimming breaks preview syntax

---

doc/completion-nvim.txt
lua/completion/hover.lua
lua/completion/signature_help.lua
plugin/completion.vim

Leverage neovim's new Api for floating windows with borders. This applies to auto_hover and signature_help

Add border to floating windows
