nvim-lua/completion-nvim

lua/completion.lua, lua/source.lua, lua/source/ts_complete.lua
This PR brings basic tree sitter integration and a treesitter completion source (for now working only for C filetype), as requested in #5.
Future work will be :
* Using treesitter for syntax changing chains
* Better treesitter source (variables in scope, ...)
=> Treesitter integration (first iteration)

lua/source/ts_complete.lua
For treesitter completion, only provide variables in scope for completion.
After some work around configuration, it should be possible to provide this kind of completion for every language, based on some variables configuring the queries used during the search in the syntax tree.
Sorry for the two PR really close one to another, now I am going to work on syntax based chains.
(#5)
=> Treesitter source : provide only variable in scope

lua/source.lua
As requested [here](https://github.com/haorenW1025/completion-nvim/issues/4#issuecomment-599558612).
=> Add ability to cycle inside the chains

ftplugin/c.vim, lua/completion.lua, lua/source/ts_complete.lua, plugin/completion.vim
Allows for more ts_complete customizability, and more stable checks.
Sorry for the really close PR.
=> ts_complete customization and stability

README.md, autoload/completion.vim, lua/completion.lua, lua/hover.lua, lua/source.lua, lua/utility.lua, plugin/completion.vim
This is basically completion chains that are used based on the curent
syntax group (customizable).
Seraching order is as follows :
* current ft current syntax group
* default current syntax group
* current ft default
* default default
Syntax group keys in scoped chain completions are regexes that will match
case insensitively the current syntax group.
EDIT: Wrong search order
=> [RFC] Scoped completion chains

README.md
Really great job on this!
I hope it's alright, but I went through the readme and standardized a couple things and fixed some grammar mistakes. I don't believe I changed the meaning of anything, but let me know if you'd like me to revert or change anything.
=> update readme and correct some typos

README.md, doc/completion-nvim.txt, lua/completion.lua, lua/completion/matching.lua, lua/completion/util.lua, lua/source/lsp.lua, lua/source/snippet.lua, plugin/completion.vim
Implement suggested feature in #66.
=> feat: multiple matching strategy

README.md, doc/completion-nvim.txt, lua/source.lua, lua/source/lsp.lua, plugin/completion.vim
Implement an option to toggle completion on delete.
Enable it by
```vim
let g:completion_trigger_on_delete = 1
```
=> feat: completion on delete(#75)

README.md, doc/completion-nvim.txt
A couple typos, one somewhat important as users might want to copy/paste the config variable.
=> DOC: tigger -> trigger, Completeion -> Completion

README.md, doc/completion-nvim.txt, lua/completion/complete.lua, plugin/completion.vim
=> deprecated: just use 'pumheight' instead of completion_max_items(#110)

doc/completion-nvim.txt, lua/completion/source.lua, lua/completion/source/snippet.lua
This PR allow multiple snippet source by just using it as a single source.
Todo:
=> rework: allow multiple snippets

lua/completion/complete.lua, lua/completion/matching.lua, lua/completion/source.lua, lua/completion/source/lsp.lua, lua/completion/source/path.lua
context aware completion inspired by coc.nvim
a gif to explain what I talking about here
On master:
On this patch:
=> feat: context aware completion

lua/completion/source.lua
=> fix: broken auto changing source

lua/completion/complete.lua, lua/completion/source/lsp.lua
=> fix: respect isIncomplete flag when perform caching

README.md
=> Add completion-tabnine link

autoload/completion.vim
=> fix: use nvim_feedkeys instead of nvim_input

autoload/completion.vim
fix https://github.com/nvim-lua/completion-nvim/issues/145
=> fix: added baskslash in nvim_feedkey (fix-issue-145)

lua/completion/source/lsp.lua, plugin/completion.vim
Make snippet expansion configurable
cc @Shatur95
=> feat: configurable snippet expansion

autoload/completion.vim, lua/completion.lua, lua/completion/complete.lua, lua/completion/hover.lua, lua/completion/manager.lua, lua/completion/source.lua, lua/completion/source/ins_complete.lua, lua/completion/source/lsp.lua
First step of refactoring, still more to come...
cc @mg979 would love to hear your feedback:)
=> refactor: move manager to a different file

lua/completion/source/snippet.lua
=> Fix fetching vsnip snippets list. Fixes #169.

README.md, doc/completion-nvim.txt, lua/completion/matching.lua
=> Add all matching strategy

lua/completion.lua, lua/completion/source.lua, lua/completion/source/snippet.lua
Separated out from #172.
cc @tjdevries
=> Add supports for snippets.nvim's own snippets

lua/completion/health.lua
Forgot that in #180.
Also did some drive-by text fixes.
=> Snippets.nvim checkhealth

lua/completion.lua
@haorenW1025  Also should be check in here. fix #194
=> fix user_data is nil

lua/completion.lua
=> auto tigger signature help window when completedone.

lua/completion/util.lua, plugin/completion.vim
=> feat: add ability to truncate completion menus

lua/completion/hover.lua
=> fix auto hover when inserting snippet items

README.md
Just a small change to include snippets.nvim support :)
=> doc: update readme to include support of snippets.nvim

README.md, autoload/completion.vim, doc/completion-nvim.txt, lua/completion.lua, plugin/completion.vim
By providing a lua alternative to tab and s-tab
This removes unneeded vim code
=> Improve trigger completion

lua/completion/util.lua
We can just use ```menu_length``` as calculated above.
=> remove unnecessary function call

lua/completion/util.lua, plugin/completion.vim
=> feat: add truncation of menu length and fix variable names

README.md, doc/completion-nvim.txt, lua/completion/matching.lua, plugin/completion.vim
This PR enables smart case matching.
=> Add option to enable smart case matching.

lua/completion/complete.lua, lua/completion/source/lsp.lua
A small rework trying to fix too many triggering of completion and popup-menus flickering.
=> fix: rework completion to fix isComplete and flickering issues

lua/completion/matching.lua
Related comment: https://github.com/nvim-lua/completion-nvim/pull/251#issuecomment-714444749
=> Fix smart and ignore case implementation to work the same way as built in.

doc/completion-nvim.txt
Also, I think the [wiki](https://github.com/nvim-lua/completion-nvim/wiki/chain-complete-support#customization-of-chain_completion_list) needs to be updated.
=> doc: fix ins-complete names

README.md
I have created a new external source for completion-nvim, and I added the repository link to Readme.md.
=> Added completion_tmux repository to Readme.md

README.md
https://github.com/neovim/nvim-lspconfig/pull/348
=> docs: Update nvim_lsp to lspconfig

README.md
https://github.com/nvim-lua/diagnostic-nvim/issues/73
=> docs: Remove deprecated diagnostic-nvim

doc/completion-nvim.txt
to account for the renaming of the repository
=> doc: update nvim-lsp by nvim-lspconfig

lua/completion/source/snippet.lua
Signed-off-by: Seb Laveze <sl8vz@users.noreply.github.com>
=> snippet: skip true items in UltiSnips list

README.md
=> doc: Mention snippets.nvim support in README

lua/completion.lua, lua/completion/source/lsp.lua, lua/completion/source/snippet.lua
=> Use opt.get_option with snippets.nvim completion

lua/completion/hover.lua
buf_request can take a callback, so let's use that :D 
(Let me know if I'm missing something)
=> completion/hover: don't override handler globally

lua/completion/signature_help.lua
=> fix: signature_help windows disapper on pressing space

lua/completion/signature_help.lua
=> fix: focus jumps into floating signature help (#376)

lua/completion.lua, plugin/completion.vim
=> feat: add disable filetype
